# Generated by Django 3.2.4 on 2021-06-13 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_restauracion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauracion',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='precio de la reparación', max_digits=10, validators=[django.core.validators.MinValueValidator('0.01')], verbose_name='Precio de la reparación'),
        ),
    ]
