# Generated by Django 3.2.4 on 2021-06-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210613_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauracion',
            name='fecha_reingreso',
            field=models.DateField(help_text='fecha de primer ingreso de la obra', null=True, verbose_name='fecha de reingreso ingreso'),
        ),
    ]
