# Generated by Django 3.2.4 on 2021-06-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_restauracion_fecha_reingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurador',
            name='domicilio',
        ),
    ]
