# Generated by Django 3.2.4 on 2021-06-14 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210614_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='valuacion',
            field=models.DecimalField(decimal_places=2, help_text='valuación en pesos', max_digits=10, validators=[django.core.validators.MinValueValidator('0.01')], verbose_name='valuación'),
        ),
    ]
