# Generated by Django 3.2.4 on 2021-06-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210614_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': (['nombre'],), 'verbose_name': ('Especialidad',), 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='tiporestauracion',
            options={'ordering': (['nombre'],), 'verbose_name': ('Tipo de restauración',), 'verbose_name_plural': 'Tipo de restauraciones'},
        ),
    ]
