# Generated by Django 3.2.4 on 2021-06-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_especialidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauracion',
            options={'ordering': ['fecha_reingreso'], 'verbose_name': ('Restauración',), 'verbose_name_plural': 'Restauraciones'},
        ),
        migrations.AlterModelOptions(
            name='tiporestauracion',
            options={'verbose_name': ('Tipo de restauración',), 'verbose_name_plural': 'Tipo de restauraciones'},
        ),
    ]
