# Generated by Django 3.2.4 on 2021-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_restauracion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauracion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='precio de la reparación', max_digits=15, verbose_name='Precio de la reparación'),
        ),
    ]
