# Generated by Django 3.2.4 on 2021-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_restauracion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='valuacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='valuación en pesos', max_digits=10, verbose_name='valuación'),
        ),
    ]
