# Generated by Django 3.2.4 on 2021-06-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_obra_valuacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='restauración',
            new_name='restauracion',
        ),
    ]
