# Generated by Django 3.2.4 on 2021-06-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_restauración_obra_restauracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestauradorEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_restauradorespecialidad_related', to='app.especialidad', verbose_name='Especialidad')),
                ('restaurador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_restauradorespecialidad_related', to='app.restaurador', verbose_name='Restaurador')),
            ],
        ),
    ]
