# Generated by Django 3.2.4 on 2021-06-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_restauradorespecialidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauradorespecialidad',
            options={'verbose_name': ('Restaurador por especialidad',), 'verbose_name_plural': 'Restaurador por especialidades'},
        ),
    ]
