# Generated by Django 3.2.4 on 2021-07-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_restauradorespecialidad_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='restauracion',
        ),
        migrations.AddField(
            model_name='obra',
            name='restauracion',
            field=models.ManyToManyField(blank=True, help_text='Restauraciones de obra', null=True, related_name='app_obra_related', to='app.Restauracion', verbose_name='Restauración'),
        ),
    ]
