# Generated by Django 3.2.4 on 2021-07-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210720_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='restauracion',
            field=models.ManyToManyField(to='app.Restauracion'),
        ),
    ]
