# Generated by Django 3.2.4 on 2021-07-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210720_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='restauracion',
        ),
        migrations.AddField(
            model_name='restauracion',
            name='obra',
            field=models.ForeignKey(help_text='Obra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_restauracion_related', to='app.obra', verbose_name='Obra'),
        ),
    ]
